services:
  udaring-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: udaring_database
    volumes:
      - type: volume
        source: udaring-volume
        target: /var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      my-application-network:
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U user -d udaring_database'" ]
      interval: 10s
      timeout: 3s
      retries: 3
  udaring-backend:
    build: .
    image: udaring-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      udaring-db:
        condition: service_healthy
    networks:
      my-application-network:
    environment:
      DB_URL: "jdbc:postgresql://udaring-db:5432/udaring_database"
      DB_USER: "user"
      DB_PASSWORD: "password"
      ACCESS_TOKEN_DURATION: "60m"
      ACCESS_TOKEN_SECRET: "access-secret"
      ACCESS_TOKEN_ISSUER: "app.co.id"
      REFRESH_TOKEN_DURATION: "3d"
      REFRESH_TOKEN_SECRET: "refresh-secret"
      TZ: Asia/Jakarta
networks:
  my-application-network:
volumes:
  udaring-volume:
