services:
  udaring-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: udaring_database
    volumes:
      - type: volume
        source: udaring-volume
        target: /var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      my-application-network:
networks:
  my-application-network:
volumes:
  udaring-volume:
