spring.application.name=udaring
spring.mvc.problemdetails.enabled=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.token.config.access-token.duration=${ACCESS_TOKEN_DURATION:60m}
app.token.config.access-token.secret=${ACCESS_TOKEN_SECRET:access-secret}
app.token.config.access-token.issuer=${ACCESS_TOKEN_ISSUER:app.co.id}
app.token.config.refresh-token.duration=${REFRESH_TOKEN_DURATION:3d}
app.token.config.refresh-token.secret=${REFRESH_TOKEN_SECRET:refresh-secret}
